sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - source # build master branch only
install:
  - npm install
  - npm install hexo-deployer-git --save
script:
  - hexo clean
  - hexo generate # generate static files
after_script:
  - git config user.name "windniw"
  - git config user.email "windniw36@gmial.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy
